# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
#- task: Maven@4
#  inputs:
#    mavenPomFile: 'pom.xml'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: 'default'
#    mavenVersionOption: 'Default'
#    mavenAuthenticateFeed: false
#    effectivePomSkip: false
#    sonarQubeRunAnalysis: false

- task: Maven@4
  displayName: Build Docker image
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'spring-boot:build-image'
    options: '-DskipTests=true'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'caijunhui/trading-bot'
    command: 'push'
    tags: |
      latest
