# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  # Command Line v2
  # Run a command line script using Bash on Linux and macOS and cmd.exe on Windows.
  - task: CmdLine@2
    inputs:
      script: wget -O graalvm-jdk.tar.gz https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz
      workingDirectory: /tmp

  # Java tool installer v1
  # Acquire a specific version of Java from a user-supplied Azure blob or the tool cache and sets JAVA_HOME.
  - task: JavaToolInstaller@1
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'LocalDirectory'
      jdkFile: '/tmp/graalvm-jdk.tar.gz'
      jdkDestinationDirectory: '/opt/graalvm'

  - task: DownloadSecureFile@1
    displayName: Download settings.xml
    inputs:
      secureFile: 'settings.xml'
    name: settingsXml

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        rm -rf ${HOME}/.m2
        mkdir ${HOME}/.m2
        cp "$(settingsXml.secureFilePath)" "${HOME}/.m2"

  #- task: Maven@4
  #  inputs:
  #    mavenPomFile: 'pom.xml'
  #    publishJUnitResults: true
  #    testResultsFiles: '**/surefire-reports/TEST-*.xml'
  #    javaHomeOption: 'JDKVersion'
  #    jdkVersionOption: 'default'
  #    mavenVersionOption: 'Default'
  #    mavenAuthenticateFeed: false
  #    effectivePomSkip: false
  #    sonarQubeRunAnalysis: false

  - task: Maven@4
    displayName: Build Docker image
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'spring-boot:build-image'
      options: '-DskipTests=true'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenOptions: '-Xmx3072m'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'caijunhui/trading-bot'
      command: 'push'
      tags: |
        latest
