[server]
port = 8086

[application]
name = "stock-bot-server"

[registry]
address = "http://127.0.0.1:8500"
token = ""
[service.check]
address = "http://127.0.0.1:8080/health/check"
interval = "30s"

[logger]
enabled = true
level = "info"
file = "stock-boot-server.log"
log_dir = "./logs"
