[server]
port = 8080

[application]
name = "stock-bot-server"

[registry]
address = "http://127.0.0.1:8500"
token = ""
[service.check]
address = "http://127.0.0.1:8080/health/check"
interval = "30s"

[logger]
enabled = true
level = "info"
file = "stock-boot-server.log"
log_dir = "./logs"

[database]
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
name = "stock"
kind = "mysql"

[stock.api.sh]
baseurl = "https://yunhq.sse.com.cn:32042"
[stock.api.sz]
baseurl = "https://www.szse.cn"

[notification]
url = "https://message.joinspace.dynv6.net"
token = ""
receiver = ""
