server:
  port: 8080

spring:
  application:
    name: trading-bot
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/stock?sslmode=require&client_encoding=utf8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


notification:
  user: ${NOTIFICATION_RECEIVER}
